version: "3.9"
services:
  front:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./front
    ports:
      - 80:80
    depends_on:
      - api
  api:
    build:
      context: .
    ports:
    - 8080:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
#    volumes:
#      - ./.docker_env:/app/.env
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
#    volumes:
#      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
#      POSTGRES_USER: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /home/sayberol/postgres_data:/var/lib/postgresql/data