version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:base
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: sayberol/todolist
    ports:
    - 8080:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
#    volumes:
#      - ./.docker_env:/app/.env
  migrations:
    image: sayberol/todolist
    depends_on:
      postgres:
        condition: service_healthy
#    volumes:
#      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
#      POSTGRES_USER: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgres